MAIN_URL1 = '/'
MAIN_URL2 = '/home'
ABOUT_URL = '/about'
ARTICLES_URL = '/articles'
NEW_URL = '/create-new-article'
CONCRETE_ARTICLE_URL = '/articles/<int:id>'
USER_URL = '/user/<string:name>/<int:id>'
